"""Folderstructure contains the folder structure previously
contained in 'AppConfig.py'. That file got too big, so it got
factored out.
"""

ADVIEZEN_CHILDREN = [
    {'id':'adv_2006', 
     'title':'2006', 
     'type':'Folder',
     'children':[]},
    {'id':'adv_2005', 
     'title':'2005', 
     'type':'Folder',
     'children':[]},
    {'id':'adv_2004', 
     'title':'2004', 
     'type':'Folder',
     'children':[]},
    {'id':'adv_2003', 
     'title':'2003', 
     'type':'Folder',
     'children':[]},
    {'id':'adv_2002', 
     'title':'2002', 
     'type':'Folder',
     'children':[]},
    {'id':'adv_2001', 
     'title':'2001', 
     'type':'Folder',
     'children':[]},
    {'id':'adv_1999', 
     'title':'1999', 
     'type':'Folder',
     'children':[]},]

ROOT_CHILDREN = [
    {'id':'voorstelling', 
     'title':'Voorstelling', 
     'type':'Folder',
     'children':[]},
    {'id':'adviezen', 
     'title':'Adviezen', 
     'type':'Folder',
     'children':ADVIEZEN_CHILDREN},
    {'id':'jaarverslag', 
     'title':'Jaarverslag', 
     'type':'Folder',
     'children':[]},
    {'id':'nieuwsbrieven', 
     'title':'Nieuwsbrieven', 
     'type':'Folder',
     'children':[]},
    {'id':'persberichten', 
     'title':'Persberichten', 
     'type':'Folder',
     'children':[]},
    {'id':'studies', 
     'title':'Studies', 
     'type':'Folder',
     'children':[]},
    {'id':'hoorzitting', 
     'title':'Hoorzittingen', 
     'type':'Folder',
     'children':[]},
    {'id':'evenementen', 
     'title':'Evenementen', 
     'type':'Folder',
     'children':[]},]
